### PR TITLE
Add ChainedNotification to handle multiple notifications at once

### PR DESCRIPTION
**Pull request by pierredup**

### CODE REVIEW

**Comment by odino** [comment]
hey @pierredup what is the use case for this?

**Comment by odino** [comment]
hey @pierredup would you have a chance to follow up?

**Comment by pierredup** [comment]
Hi @odino Sorry I missed your first comment.

I needed this in a project I'm working on, where multiple notifications can be triggered from different places. So each notification is added to the chained handler, then it triggers all the notifications in the handler in one place.

I've worked around this by registering custom handlers in my project, but I thought this might be useful for somebody else, but if you don't see a need for it, feel free to close this PR as I already have what I need.

**Comment by odino** [comment]
ok, closing as I think this is a very specific need -- though Im open to giving it a second thought if anyone feels like it's very useful for their use case!

**Pull request closed without merging**
